############################################
# microservice 0.1.0
# author: Hervé Beraud
# url: https://https://github.com/microservice-toolbox/microservice
# Autogenerated with https://github.com/microservice-core/project-builder
# Uages :
# -------
# Pull
# docker pull microservice-toolbox/microservice:latest
# Run from registry
# docker run microservice-toolbox/microservice
# Build localy
# docker build -t microservice .
############################################


FROM python:3-onbuild
WORKDIR /usr/src/app/sources
CMD [ "sh", "run.sh" ]
EXPOSE 80


